### ISSUE TITLE
automatic update not work

### ISSUE THREAD

**Issue by KOTBCTAKAHE** [atageldi194229/pinging-server#4]
automatic update does not work, I checked index.js and it seems to expect a response in JSON, although it doesn't have a JSON structure at all.

**Comment by KOTBCTAKAHE** [comment]
I can try to fix it

**Comment by KOTBCTAKAHE** [comment]
#6  pull request created. @atageldi194229 @haitovs

**Comment by atageldi194229** [comment]
Old version got JSON data from another API

**Comment by KOTBCTAKAHE** [comment]
> Old version got JSON data from another API

which api?
